gazebo_ros_control:
  pid_gains:
    J1: {p: 100.0, i: 0.1,  d: 1.0}
    J2: {p: 100.0, i: 0.1,  d: 1.0}
    J3: {p: 100.0, i: 0.1,  d: 1.0}
    J4: {p: 100.0, i: 0.1,  d: 1.0}
    J5: {p: 100.0, i: 0.1,  d: 1.0}
    J6: {p: 100.0, i: 0.1,  d: 1.0}