teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
      z: 3
    scale_linear:
      x: 0.7
      y: 0.7
      z: 0.7

    axis_angular:
      yaw: 5
      pitch: 2
      roll: 7
    scale_angular:
      yaw: 0.4
      pitch: 0.4
      roll: 0.4

    enable_button: -1
    require_enable_button: false
    publish_stamped_twist: true
    frame: 'base_link'