manipulator:
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  #kinematics_solver: SR80_manipulator/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  solve_type: Speed ## track_ik params
  
  #kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  #opw_kinematics_geometric_parameters:
  #  a1:  0.175
  #  a2:  -0.206
  #  b:   0.000
  #  c1:  0.630
  #  c2:  0.905
  #  c3:  1.020
  #  c4:  0.250
  #opw_kinematics_joint_offsets: [0, 0, -1.57079632679, 0, 0, 0]
  #opw_kinematics_joint_sign_corrections: [1, -1, -1, 1, -1, 1]