manipulator_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - J1
    - J2
    - J3
    - J4
    - J5
    - J6
  gains:
    J1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
pos_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - J1
    - J2
    - J3
    - J4
    - J5
    - J6
  gains:
    J1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      J1: {trajectory: 0.1, goal: 0.1}
      J2: {trajectory: 0.1, goal: 0.1}
      J3: {trajectory: 0.1, goal: 0.1}
      J4: {trajectory: 0.1, goal: 0.1}
      J5: {trajectory: 0.1, goal: 0.1}
      J6: {trajectory: 0.1, goal: 0.1}
vel_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - J1
    - J2
    - J3
    - J4
    - J5
    - J6
  gains:
    J1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - J1
    - J2
    - J3
    - J4
    - J5
    - J6
  # J1:
  #  pid: {p: 100.0, i: 1.0, d: 1.0}
  #J2:
  #  pid: {p: 100.0, i: 1.0, d: 1.0}
  #J3:
  #  pid: {p: 100.0, i: 1.0, d: 1.0}
  #J4:
  #  pid: {p: 100.0, i: 1.0, d: 1.0}
  #J5:
  #  pid: {p: 100.0, i: 1.0, d: 1.0}
  #J6:
  #  pid: {p: 100.0, i: 1.0, d: 1.0}