controller_list:
  - name: manipulator_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
  - name: pos_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
  - name: vel_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6